Traceback (most recent call last):
  File "/u/antor/u12/alochab/cs578/Lottery-Ticket-Hypothesis-in-Pytorch/LTH.py", line 330, in <module>
    main(args, ITE=1)
  File "/u/antor/u12/alochab/cs578/Lottery-Ticket-Hypothesis-in-Pytorch/LTH.py", line 69, in main
    model = eval(model_archs[args.arch_type])().to(device)
  File "<string>", line 1, in <module>
NameError: name 'fc1' is not defined
Traceback (most recent call last):
  File "/u/antor/u12/alochab/cs578/Lottery-Ticket-Hypothesis-in-Pytorch/LTH.py", line 330, in <module>
    main(args, ITE=1)
  File "/u/antor/u12/alochab/cs578/Lottery-Ticket-Hypothesis-in-Pytorch/LTH.py", line 69, in main
    model = eval(model_archs[args.arch_type])().to(device)
  File "<string>", line 1, in <module>
NameError: name 'fc1' is not defined
